spring.application.name=store
spring.datasource.url=jdbc:postgresql://localhost:5432/sandbox
spring.datasource.username=postgres
spring.datasource.password=spring123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true